project:
  type: website
  output-dir: docs

website:
  title: "StatKit Documentation"
  image: "logo.png"
  favicon: "favicon.ico"
  navbar:
    logo: logo.png
    logo-alt: "StatKit logo."
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    contents: 
      - section: "Getting Started"
        contents:
          - href: index.qmd
            text: "Home"
          - href: content/getting-started.qmd
            text: "Quick Start"
          - href: about.qmd
            text: "About"
      - section: "Tests"
        contents:
          - href: content/statistical-tests/descriptive-statistics.qmd
            text: "Descriptive Statistics"
          - href: content/statistical-tests/t-tests.qmd
            text: "T-Tests"
          - href: content/statistical-tests/anova.qmd
            text: "ANOVA"
          - href: content/statistical-tests/regression.qmd
            text: "Regression"
          - href: content/statistical-tests/neural-networks.qmd
            text: "Neural Networks"
      - section: "Help"
        contents:
          - href: content/help/faq.qmd
            text: "FAQ"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true